version: "3"
services:
  postgres-pipeline:
    hostname: postgres-pipeline
    container_name: postgres-pipeline
    image: postgres
    shm_size: 4gb
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data 
    networks:
      - pipeline-data-net

  nifi:
    image: apache/nifi:latest
    hostname: nifi
    container_name: nifi
    ports:
      - 8080:8080 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper-nifi:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    networks:
      - pipeline-data-net
    volumes:
      - /nifi:/data

networks:
  pipeline-data-net:
    driver: bridge